name:                hw-struct
version:             0.1.0.0
github:              "githubuser/hw-struct"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hw-struct#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- attoparsec
- bytestring
- ekg
- ekg-core
- http-types
- pretty
- scientific
- text
- unordered-containers
- vector
- wai
- warp

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2

executables:
  hw-struct-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-struct

tests:
  hw-struct-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-struct
